build:
	@javac com/truecaller/examples/sdk/profile/VerificationDemo.java

clean:
	@rm com/truecaller/examples/sdk/profile/*.class

help:
	@echo "To compile, execute:"
	@echo "   make build"
	@echo "To clean, execute:"
	@echo "   make clean"
	@echo "To run, execute:"
	@echo "   java com.truecaller.examples.sdk.profile.VerificationDemo payload signature [publicKey] [keyType] [signatureAlgorithm]"
